### ISSUE TITLE
Ajouter l'info "c'est au tour de" sur l'écran

### ISSUE THREAD

**Issue by Liloubhe** [bastienbarthet/schotten-totten#10]
Lorsqu'on regarde l'écran principal, on ne sait pas à qui est-ce le tour. L'info pourrait être rajouté par une en-tête/pied de page ("Player ONE/TWO") éventuellement colorée pour que ça soit plus visuel. Ou en colorant le fond de l'écran mais ça fera peut-être beaucoup de couleurs.

**Comment by bastienbarthet** [comment]
L'info est déjà présente au dessus du plateau de jeu, mais elle est quasiment invisible car blanc sur blanc .....
Cela dépend des couleur par defaut de la version d'android.
Il y a déjà un bug ouvert à ce sujet : 
[https://github.com/bastienbarthet/schotten-totten/issues/6](url)

**Comment by bastienbarthet** [comment]
Corrected
