### ISSUE TITLE
Problème de capture d'une borne

### ISSUE THREAD

**Issue by Liloubhe** [bastienbarthet/schotten-totten#11]
J'ai pu capturer une borne (remplie de 9) alors que la colonne en face n'était pas compète et aurait pu me dépasser (7/8 verts, pas de 6 ou de 9 verts visibles à ce moment là)

**Comment by bastienbarthet** [comment]
En effet la partie capture d'une borne de type 3-n est pour l'instant libre.
L'algorithme de "preuve" de capture d'une borne sera implémenté après la correction des bugs.
Une liste des tâches est disponible ici : [https://github.com/bastienbarthet/schotten-totten/projects/1](url)

**Comment by bastienbarthet** [comment]
la partie capture d'une borne de type 3-n est implémentée
