### ISSUE TITLE
Pouvoir revoir le plateau une fois un vainqueur trouvé

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#16]
Popup "ONE wins", apres avoir cliqué OK il serait cool de pouvoir revoir le plateau de jeu, et de choisir quand quitter par un bouton. apres le OK, actuellement retour au bureau android.

**Comment by bastienbarthet** [comment]
apres le popup de fin du jeu, le plateau et visible et on quitte en cliquant sur le bouton "fin du tour"
