### ISSUE TITLE
bug : reclamation de borne sur du wild hand

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#17]
882 non coloré .VS. 676 non coloré (donc 18 contre 19 en valeur). Reclamer la borne coté 882 est possible

![screenshot_2017-01-15-16-39-00](https://cloud.githubusercontent.com/assets/15614863/21963900/616f55ec-db42-11e6-8eea-74ec33300769.png)

**Comment by bastienbarthet** [comment]
probleme corrige.

nouvelle version de la méthode "sideStrength" de la classe "Milestone" : 

    private int sideStrength(final List<Card> side) {
        if (side.size() != MAX_CARDS_PER_SIDE) {
            return 0;
        } else {
            final List<Integer> numbers = new ArrayList<>();
            int sum = 0;
            boolean isFlush = true;
            boolean is3OfKind = false;
            
            // check flush
            final Card.COLOR firstCardColor = side.get(0).getColor();
            for (final Card card : side) {
            	if (!card.getColor().equals(firstCardColor)) {
            		isFlush = false;
            		break;
            	}
            }
            
            // check straight
            for (final Card card : side) {
                final int n = card.getNumber().ordinal();
                sum += n;
                numbers.add(n);
            }
            Collections.reverse(numbers);
            boolean isStraight = false;
            for (int i = 1; i < numbers.size(); i++) {
                isStraight = (numbers.get(i) == numbers.get(0) - i);
            }

            // return strength
            if (isStraight && isFlush) {
                // straight flush
                return sum + 500;
            } else if (is3OfKind) {
                // 3 of a kind
                return sum + 400;
            } else if (isFlush) {
                // flush
                return sum + 300;
            } else if (isStraight) {
                // straight
                return sum + 200;
            } else {
                // wild hand
                return sum + 100;
            }
        }
    }

Ajout d'un nouveau test : 
    @Test
    public void WildHandTest_2() throws MilestoneSideMaxReachedException {
        // play one
        testMilestone.addCard(new Card(Card.NUMBER.EIGHT, Card.COLOR.CYAN), PlayerType.ONE);
        testMilestone.addCard(new Card(Card.NUMBER.EIGHT, Card.COLOR.BLUE), PlayerType.ONE);
        testMilestone.addCard(new Card(Card.NUMBER.TWO, Card.COLOR.CYAN), PlayerType.ONE);

        // player two
        testMilestone.addCard(new Card(Card.NUMBER.SIX, Card.COLOR.GREY), PlayerType.TWO);
        testMilestone.addCard(new Card(Card.NUMBER.SEVEN, Card.COLOR.GREY), PlayerType.TWO);
        testMilestone.addCard(new Card(Card.NUMBER.SIX, Card.COLOR.GREEN), PlayerType.TWO);

        Assert.assertFalse(testMilestone.reclaim(PlayerType.ONE));
        Assert.assertTrue(testMilestone.reclaim(PlayerType.TWO));
    }

**Comment by bastienbarthet** [comment]
correction published
