### ISSUE TITLE
un tour de sauté pour joueur 1...

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#21]
J1 a joué 3 fois, J2 a joué 4 fois. Cela devrait etre au tour de J1 mais c'est à J2...
![screenshot_20170122-135406](https://cloud.githubusercontent.com/assets/15614863/22182635/7f0a0a1c-e0aa-11e6-911e-57902f20cd7a.png)

**Comment by bastienbarthet** [comment]
non reproductible
