### ISSUE TITLE
reclamer 111 contre 187 (couleur) n'est pas possible

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#26]
![screenshot_2017-01-28-16-44-26](https://cloud.githubusercontent.com/assets/15614863/22397776/7065c9c8-e579-11e6-9cd2-6003ed2337f8.png)

reclamer 111 contre 187 (couleur) n'est pas possible

**Comment by bastienbarthet** [comment]
mauvais calcul du 3 ok e kind résolu
