### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#27]
![screenshot_2017-01-28-16-45-13](https://cloud.githubusercontent.com/assets/15614863/22397780/892d5fe8-e579-11e6-9839-111f25996000.png)

Trouver l'erreur je ne sais pas, mais mettre un catch global qui te retourne la trace pourrait t'aider?

**Comment by bastienbarthet** [comment]
Ajout de la stack trace dans le message d'erreur.
