### ISSUE TITLE
Error : The deck is empty.

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#28]
stackstrace lorsqu'il n'y a plus de carte : 
Deck.drawCard(Deck.java:32)
EmptyDeckException

**Comment by BastienLeh** [comment]
capture d'écran si besoin

**Comment by BastienLeh** [comment]
situation juste avant
![screenshot_2017-02-28-12-48-26](https://cloud.githubusercontent.com/assets/15614863/23404550/ddd85706-fdb5-11e6-9132-94c731180f35.png)

**Comment by bastienbarthet** [comment]
Probleme corrigé
