### ISSUE TITLE
crash lors d'une reclamation de borne

### ISSUE THREAD

**Issue by BastienLeh** [bastienbarthet/schotten-totten#8]
cf capture d'écran, crash lorsque l'utilisateur essai de reclamer la borne 888 (qui gagne contre le 222 d'en face)
![screenshot_2016-12-15-10-34-59](https://cloud.githubusercontent.com/assets/15614863/21218908/d6ee281e-c2b2-11e6-9856-3edb7d6cd464.png)

**Comment by bastienbarthet** [comment]
problème résolu, modification de la façon de vérifier la force d'uje combinaison
